name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      # Get local dependencies
      - run: npm install
      - run: npm run createIcons

