name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: ci
        run: npm ci
      - name: pack
        run: npm run vscode:package
      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
          fail_on_unmatched_files: true
      - name: publish
        run: npm run vscode:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
