name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: ci
        run: npm ci
      - name: pack
        run: npm run vscode:package
      - name: github release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          fail_on_unmatched_files: true
      - name: publish
        run: npm run vscode:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
