name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - name: pack
        run: pnpm run vscode:package
      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
          fail_on_unmatched_files: true
      - run: pnpm run vscode:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
